### ISSUE TITLE
use libdparse from dlang-community as dependency

### ISSUE THREAD

**Issue by stefan-koch-sociomantic** [dlang-community/dfmt#291]
Is there any reason why we use libdparse from hackerpilots repo instead of using the dlang-community one ? 

It does make it harder to add features to dfmt which depend on libdparse changes.

**Comment by ZombineDev** [comment]
Since @Hackerpilot transferred his libdparse repo to the dlang-community organization, GitHub automatically redirects https://github.com/Hackerpilot/libdparse to https://github.com/dlang-community/libdparse, so it shouldn't matter which URL you use.
That said, if you wish you can open pull-request to rename all references from  Hackerpilot/[repo name] to dlang-community/[repo name], to avoid confusion in the future.

**Comment by ZombineDev** [comment]
Now that https://github.com/dlang-community/dfmt/pull/292 is about to be merged, I guess we can close this issue.
