### ISSUE TITLE
Downgrade libdparse

### ISSUE THREAD

**Issue by WebFreak001** [dlang-community/dfmt#344]
using dfmt in projects using another libdparse version is a pain since the latest upgrade because it references 0.8.0-alpha. As it is just an alpha it would be hard convincing all the other package maintainers to upgrade to this release, therefore I think dfmt should rather be downgraded until there is a stable libdparse release.

```
Root package workspace-d reference libdparse >=0.0.0 cannot be satisfied.
Packages causing the conflict:
	dfmt depends on >=0.8.0-alpha.5 <0.9.0
	workspace-d depends on >=0.0.0
	fluent-asserts:core depends on >=0.7.2-alpha.3 <0.8.0-0
	fluent-asserts depends on >=0.7.2-alpha.3 <0.8.0-0
	dsymbol depends on ~>0.7.1
	dsymbol depends on >=0.7.1-beta.7 <0.8.0
	dsymbol depends on >=0.7.1-beta.7 <0.8.0
	dsymbol depends on >=0.7.1-beta.7 <0.8.0
	libddoc depends on >=0.7.0-alpha10 <0.8.0
	dscanner depends on >=0.7.2-alpha.5 <0.8.0-0
```

See Pure-D/workspace-d#87

**Comment by skl131313** [comment]
I guess this is the risk you take when you use the library instead of just an external process. I don't think it should be downgraded, just use an older version. The reason for the bump in the major version of dfmt was partially because of the breaking changed with libdparse iirc. Stick with version 0.5.3 until you can upgrade to 0.6.*.

**Comment by WebFreak001** [comment]
hm well I depended on 0.6.0-alpha.1 because it had the old libdparse which I guess was expected to break on upgrades though because of the alpha.
